export const routes = {
  splash: "/",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  goal: "/onboarding/goal",
  home: "/home",
  workout: "/workout",
  workoutPlan: (id: string) => `/workout/plan/${id}` as const,
  workoutSession: (id: string) => `/workout/session/${id}` as const,
  workoutHistory: "/workout/history",
  workoutHistoryItem: (id: string) => `/workout/history/${id}` as const,
  exercises: "/workout/exercises",
  exercise: (slug: string) => `/workout/exercises/${slug}` as const,
  customReview: "/workout/custom/review",
  guidance: "/workout/guidance",
  beginnerPlans: "/workout/plans",
  formPosture: "/workout/form",
  diet: "/diet",
  dietAdd: "/diet/add",
  dietEdit: (id: string) => `/diet/${id}` as const,
  profile: "/profile",
  profileEdit: "/profile/edit",
  progress: "/progress",
  coach: "/coach",
  settings: "/settings",
  terms: "/legal/terms",
  privacy: "/legal/privacy",
} as const;
